services:
  - type: web
    name: financial-warfare
    env: docker
    repo: https://github.com/financewar6-arch/financialwarfare.git
    region: oregon
    plan: free
    healthCheckPath: /
    envVars:
      - key: NEXTAUTH_SECRET
        value: WIzPGvjB2ZGtakMiHqT2Nh7gLEYJvrDM1QMOHpyz5Ro=
      - key: NEXTAUTH_URL
        fromService:
          name: financial-warfare
          property: host
          suffix: /
      - key: ALPHA_VANTAGE_API_KEY
        value: FYTQR83WLU2TXK0U
      - key: FINNHUB_API_KEY
        value: 97f5069e61c14610b4ee9ab910b9a9e9
      - key: GOLD_API_KEY
        value: 596994ade4b99a951cb019c36eb75be7b9ed04182297ff7a2ba0fcf457715e83
      - key: NEWSAPI_KEY
        value: 97f5069e61c14610b4ee9ab910b9a9e9
      - key: NEXTAUTH_TRUST_HOST
        value: "true"
